const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=__dirname, storePath=path.join(root,'piremaxx-data.json'), externalDataPath='D:\\Piremaxx\\Diego\\dados';
const seed={users:[{id:1,name:'Administrador',email:process.env.PIREMAXX_ADMIN_EMAIL||'admin@example.invalid',password:process.env.PIREMAXX_ADMIN_PASSWORD||''}],clients:[],products:[],sales:[],purchases:[],finance:[],settings:{company:'Piremaxx Pneus Premium'}};
let db=fs.existsSync(storePath)?JSON.parse(fs.readFileSync(storePath,'utf8')):seed;
db={...seed,...db,clients:db.clients||[],products:db.products||[],sales:db.sales||[],purchases:db.purchases||[],finance:db.finance||[]};
function htmlXlsRows(file){if(!fs.existsSync(file))return[];const html=fs.readFileSync(file,'latin1'),rows=[...html.matchAll(/<tr[\s\S]*?<\/tr>/gi)].map(m=>[...m[0].matchAll(/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(x=>x[1].replace(/<[^>]+>/g,'').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').trim()));if(rows.length<2)return[];const h=rows[0].map(x=>x.toLowerCase());return rows.slice(1).filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]||''])))}
function importExternalData(){if(!fs.existsSync(externalDataPath)||db.settings?.externalImportAt)return;const p=n=>htmlXlsRows(path.join(externalDataPath,n));const contacts=p('contatos.xls'),products=p('produtos.xls'),sales=p('vendas.xls'),purchases=p('compras.xls'),finance=p('financeiro.xls');if(!db.clients.length)db.clients=contacts.map((x,i)=>({id:x.codigo||`imp-c-${i+1}`,name:x.nome||'',tradeName:x.fantasia||'',doc:x.cpfcnpj||'',phone:x.fones||'',email:x.emails||'',address:x.end||'',number:x.num||'',neighborhood:x.bairro||'',city:x.cidadenome||'',state:x.uf||'',zip:x.cep||'',tags:x.tags||'',active:x.ativo!=='0',source:'contatos.xls'}));if(!db.products.length)db.products=products.map((x,i)=>({id:x.codigo||`imp-p-${i+1}`,name:x.nome||x.descricao||'',sku:x.codigo||'',price:x.preco||x.valor||'0',stock:x.estoque||x.qtd||'0',category:x.categoria||'',active:x.ativo!=='0',source:'produtos.xls'}));if(!db.sales.length)db.sales=sales.map((x,i)=>({...x,id:x.codigo||`imp-v-${i+1}`,customer:x.cliente||x.contato||x.nome||'',value:x.valor||x.total||'0',date:x.data||x.dtcad||'',source:'vendas.xls'}));if(!db.purchases.length)db.purchases=purchases.map((x,i)=>({...x,id:x.codigo||`imp-comp-${i+1}`,supplier:x.fornecedor||x.contato||x.nome||'',value:x.valor||x.total||'0',date:x.data||x.dtcad||'',source:'compras.xls'}));if(!db.finance.length)db.finance=finance.map((x,i)=>({...x,id:x.codigo||`imp-fin-${i+1}`,description:x.descricao||x.nome||'',value:x.valor||x.total||'0',type:x.tipo||x.natureza||'',date:x.data||x.vencimento||'',source:'financeiro.xls'}));db.settings={...(db.settings||{}),externalImportAt:new Date().toISOString(),externalSource:externalDataPath};save()}
importExternalData();
function normalizeImported(){const num=v=>{const s=String(v??'0').trim();return Number(s.includes(',')?s.replace(/\./g,'').replace(',','.'):s)||0};const contactNames=new Map(db.clients.map(x=>[String(x.id),x.name]));const rawProducts=htmlXlsRows(path.join(externalDataPath,'produtos.xls'));const rawById=new Map(rawProducts.map(x=>[String(x.codigo),x]));db.products=db.products.map(x=>{const r=rawById.get(String(x.id))||{};return {...x,name:x.name||r.ixprod||r.icprod||'',price:num((!x.price||x.price==='0')?r.precovenda:x.price),stock:num((!x.stock||x.stock==='0')?r.estoque:x.stock)}});db.sales=db.sales.map(x=>({...x,customer:x.customer||contactNames.get(String(x.codcontato))||'',date:x.date||x.dtvenda||x.dtcad||'',total:num((!x.total||x.total==='0')?x.valortotal:x.total),value:num((!x.value||x.value==='0')?x.valortotal:x.value),kind:x.kind||'Venda'}));db.finance=db.finance.map(x=>({...x,value:num(x.value||x.valor),paid:num(x.valorpago),date:x.date||x.dtvenc||x.dtcad||''}));if(db.settings?.externalImportAt)save()}
normalizeImported();
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.json':'application/json','.webmanifest':'application/manifest+json; charset=utf-8'};
function save(){fs.writeFileSync(storePath,JSON.stringify(db,null,2))}
function csv(rows){if(!rows.length)return '';const cols=[...new Set(rows.flatMap(x=>Object.keys(x)))];const q=v=>'"'+String(v??'').replace(/"/g,'""')+'"';return [cols.map(q).join(';'),...rows.map(x=>cols.map(c=>q(x[c])).join(';'))].join('\r\n')}
function parseCsv(text){const lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/);if(lines.length<2)return [];const cols=lines.shift().split(';').map(x=>x.replace(/^"|"$/g,'').replace(/""/g,'"'));return lines.map(line=>{const vals=[];let cur='',quoted=false;for(const ch of line){if(ch==='"')quoted=!quoted;else if(ch===';'&&!quoted){vals.push(cur);cur=''}else cur+=ch}vals.push(cur);return Object.fromEntries(cols.map((c,i)=>[c,vals[i]?.replace(/^"|"$/g,'').replace(/""/g,'"')||'']))})}
function send(res,status,data,type='application/json'){res.writeHead(status,{'Content-Type':type,'Access-Control-Allow-Origin':'*'});res.end(type.startsWith('application/json')?JSON.stringify(data):data)}
function body(req){return new Promise((ok,fail)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>{try{ok(s?JSON.parse(s):{})}catch(e){fail(e)}})})}
function id(){return crypto.randomUUID()}
async function api(req,res,url){if(req.method==='OPTIONS')return send(res,204,{});if(url==='/api/health')return send(res,200,{ok:true,app:'Piremaxx Gestor'});if(url==='/api/login'&&req.method==='POST'){const b=await body(req),u=db.users.find(x=>x.email===b.email&&x.password===b.password);return u?send(res,200,{token:'local-session',user:{id:u.id,name:u.name,email:u.email}}):send(res,401,{error:'Credenciais inválidas'})}if(url==='/api/backup'&&req.method==='GET')return send(res,200,{...db,meta:{app:'Piremaxx Gestor',version:1,createdAt:new Date().toISOString()}});if(url.match(/^\/api\/(clients|products|sales|purchases|finance)\.csv$/)&&req.method==='GET'){const key=url.split('/')[2].split('.')[0];return send(res,200,csv(db[key]),'text/csv; charset=utf-8')}if(url==='/api/import/csv'&&req.method==='POST'){const b=await body(req),key=b.resource;if(!['clients','products','sales','purchases','finance'].includes(key)||typeof b.csv!=='string')return send(res,400,{error:'Recurso ou CSV inválido'});const rows=parseCsv(b.csv).map(x=>({...x,id:x.id||id(),importedAt:new Date().toISOString()}));db[key].push(...rows);save();return send(res,201,{resource:key,count:rows.length})}if(url==='/api/restore'&&req.method==='POST'){const b=await body(req);if(!b||typeof b!=='object')return send(res,400,{error:'Backup inválido'});db={...seed,...b};save();return send(res,200,{ok:true})}const m=url.match(/^\/api\/(clients|products|sales|purchases|finance)(?:\/([^/]+))?$/);if(m){const key=m[1],itemId=m[2];if(req.method==='GET')return send(res,200,itemId?db[key].find(x=>String(x.id)===itemId)||null:db[key]);if(req.method==='POST'){const b=await body(req),item={...b,id:b.id||id(),createdAt:new Date().toISOString()};db[key].push(item);save();return send(res,201,item)}if(req.method==='PUT'&&itemId){const i=db[key].findIndex(x=>String(x.id)===itemId);if(i<0)return send(res,404,{error:'Registro não encontrado'});db[key][i]={...db[key][i],...(await body(req)),updatedAt:new Date().toISOString()};save();return send(res,200,db[key][i])}if(req.method==='DELETE'&&itemId){db[key]=db[key].filter(x=>String(x.id)!==itemId);save();return send(res,204,{})}}return send(res,404,{error:'Rota não encontrada'})}
const server=http.createServer(async(req,res)=>{const url=decodeURIComponent(req.url.split('?')[0]);try{if(url.startsWith('/api/'))return await api(req,res,url);let p=url==='/'?'/index.html':url;if(p.startsWith('/icons/'))p='/public'+p;let f=path.join(root,p);if(!f.startsWith(root)||!fs.existsSync(f))return send(res,404,'Not found','text/plain');let content=fs.readFileSync(f);if(path.extname(f)==='.html'){const isIndex=p.endsWith('/index.html');let html=content.toString().replace('</head>','<link rel="manifest" href="/manifest.webmanifest"><meta name="theme-color" content="#354a54"><link rel="apple-touch-icon" href="/icons/icon%20192.png">'+(!isIndex?'<link rel="stylesheet" href="/shell.css?v=8">':'')+'</head>');html=html.replace('</body>','<script src="/pwa.js?v=2"></script>'+(!isIndex?'<script src="/shell.js?v=8"></script>':'')+'</body>');content=Buffer.from(html)}send(res,200,content,mime[path.extname(f)]||'application/octet-stream')}catch(e){send(res,500,{error:e.message})}});const port=Number(process.env.PORT||3000);server.listen(port,()=>console.log(`Piremaxx Gestor em http://localhost:${port}`));process.on('SIGINT',()=>{save();server.close()});
function pdfSafe(value){return String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7E]/g,'').replace(/[\\()]/g,' ')}
function pdfMoney(value){const raw=String(value??'0');const n=typeof value==='number'?value:(Number(raw.includes(',')?raw.replace(/\./g,'').replace(',','.'):raw)||0);return n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}).replace(/[\u00A0]/g,' ')}
function pdfCell(value,width,font=7){const text=pdfSafe(value),limit=Math.max(4,Math.floor(width/(font*.52)));return text.length>limit?text.slice(0,Math.max(1,limit-3))+'...':text}
function makeTablePdf(title,headers,rows,widths){const pageW=595.28,pageH=841.89,left=28,top=806,rowH=14,headerH=22,bottom=34,font=7,totalW=widths.reduce((a,b)=>a+b,0);const perPage=Math.max(1,Math.floor((top-headerH-bottom)/rowH));const pages=[];for(let start=0;start<rows.length||start===0;start+=perPage){const chunk=rows.slice(start,start+perPage),c=[];const rect=(color,x,y,w,h)=>c.push(`${color} rg ${x.toFixed(2)} ${y.toFixed(2)} ${w.toFixed(2)} ${h.toFixed(2)} re f`);const text=(x,y,size,value,bold=false)=>c.push(`BT /${bold?'F2':'F1'} ${size} Tf 1 0 0 1 ${x.toFixed(2)} ${y.toFixed(2)} Tm (${pdfSafe(value)}) Tj ET`);text(left,top+8,13,title,true);text(left,top-8,7,`Gerado em ${new Date().toLocaleString('pt-BR')} - ${rows.length} registros`);let y=top-34,x=left;rect('0.35 0.47 0.52',left,y-headerH+4,totalW,headerH);headers.forEach((h,i)=>{text(x+5,y-11,7,h,true);x+=widths[i]});y-=headerH;chunk.forEach((row,index)=>{const bottomY=y-rowH+3;if(index%2===0)rect('0.94 0.94 0.94',left,bottomY,totalW,rowH);x=left;row.forEach((value,i)=>{text(x+5,y-10,font,pdfCell(value,widths[i],font));x+=widths[i]});y-=rowH});text(left,24,7,`Pagina ${pages.length+1}`);pages.push(c.join('\\n'))}const objects=[];objects[1]='<< /Type /Catalog /Pages 2 0 R >>';objects[3]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';objects[4]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>';const pageRefs=[];pages.forEach((content,i)=>{const contentObj=5+i*2,pageObj=6+i*2;objects[contentObj]=`<< /Length ${Buffer.byteLength(content,'latin1')} >>\\nstream\\n${content}\\nendstream`;objects[pageObj]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageW} ${pageH}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentObj} 0 R >>`;pageRefs.push(`${pageObj} 0 R`)});objects[2]=`<< /Type /Pages /Kids [${pageRefs.join(' ')}] /Count ${pages.length} >>`;let out='%PDF-1.4\\n%Piremaxx Gestor\\n',offsets=[0];for(let i=1;i<objects.length;i++){offsets[i]=Buffer.byteLength(out,'latin1');out+=`${i} 0 obj\\n${objects[i]}\\nendobj\\n`}const xref=Buffer.byteLength(out,'latin1');out+=`xref\\n0 ${objects.length}\\n0000000000 65535 f \\n`;for(let i=1;i<objects.length;i++)out+=`${String(offsets[i]).padStart(10,'0')} 00000 n \\n`;out+=`trailer\\n<< /Size ${objects.length} /Root 1 0 R >>\\nstartxref\\n${xref}\\n%%EOF`;return Buffer.from(out,'latin1')}
function sendPdf(res,data,name){res.writeHead(200,{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="${name}"`,'Cache-Control':'no-store'});res.end(data)}
const apiWithReports=api;api=async function(req,res,url){if(req.method==='GET'){if(['/api/reports/clients.pdf','/api/reports/contacts.pdf','/api/clients.pdf','/api/contacts.pdf'].includes(url)){const rows=db.clients.map(x=>[x.id,x.name,x.doc,x.phone,x.email,[x.city,x.state].filter(Boolean).join('/')]);return sendPdf(res,makeTablePdf('Contatos - Clientes',['Cod','Nome / Razao Social','CPF / CNPJ','Fones','E-mail','Cidade / UF'],rows,[38,205,82,76,112,54]),'contatos.pdf')}if(['/api/reports/products.pdf','/api/products.pdf'].includes(url)){const rows=db.products.map(x=>[x.id,x.name,x.sku,pdfMoney(x.price),x.stock,x.category]);return sendPdf(res,makeTablePdf('Produtos e servicos',['Cod','Produto','Codigo proprio','Preco de venda','Estoque','Categoria'],rows,[38,220,90,90,55,65]),'produtos.pdf')}}return apiWithReports(req,res,url)};
const sendPdfOriginal=sendPdf;sendPdf=(res,data,name)=>{if(Buffer.isBuffer(data)){let text=data.toString('latin1').replaceAll('\\n','\n');text=text.replaceAll('BT /F1','0 0 0 rg BT /F1').replaceAll('BT /F2 7 Tf','1 1 1 rg BT /F2 7 Tf').replaceAll('BT /F2 13 Tf','0 0 0 rg BT /F2 13 Tf').replace(/0 0 0 rg BT \/F1 7 Tf 1 0 0 1 [0-9.]+ 24\.00 Tm \(Pagina [^)]+\) Tj ET/g,'');data=Buffer.from(text,'latin1')}return sendPdfOriginal(res,data,name)};
const apiContactsOriginal=api;api=async function(req,res,url){if(req.method==='GET'&&['/api/reports/clients.pdf','/api/reports/contacts.pdf','/api/clients.pdf','/api/contacts.pdf'].includes(url)){const rows=db.clients.filter(x=>String(x.name||'').trim()).sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'pt-BR')).slice(0,100).map(x=>[x.id,x.name,x.phone,x.tags,[x.city,x.state].filter(Boolean).join('/')]);return sendPdf(res,makeTablePdf('CLIENTES',['COD','NOME','FONES','PALAVRAS-CHAVE','CIDADE/UF'],rows,[50,225,110,110,72]),'contatos.pdf')}return apiContactsOriginal(req,res,url)};
